[package]
name = "edge-motion"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
imageproc = "0.25.0"
itertools = "0.13.0"
rayon = "1.10.0"
tokio = { version = "1.39.2", features = ["full"] }
clap = { version = "4.5.11", features = ["derive", "color", "suggestions"] }